#!/bin/bash
#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

DIR=$(mktemp -d)
TO=${DIR}/issue1254.jar
SLIME="$(dirname $0)/../../.."
${SLIME}/jsh ${SLIME}/jrunscript/jsh/tools/shell.jsh.js package --script ${SLIME}/jrunscript/jsh/test/jsh-data.jsh.js --to ${TO}
echo ${TO}
${SLIME}/local/jdk/default/bin/java -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y -jar ${TO}
