#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

name: slime

services:
  # Produces a stateful, persistent SLIME container with a built-in Webtop desktop and the source directory mounted. Local changes
  # (to the local/ subdirectory, like installing JDKs, Rhino, Tomcat, and so forth) will persist between runs.
  #
  # Also used by the devcontainer implementation.
  #
  # The primary user interface for the container is Webtop (HTTP on 3000 and HTTPS on 3001 in-container).
  # The chrome and firefox services are still started so that the container can emulate the CI tests for debugging CI-only failures
  # via the contributor/devcontainer/check script.
  local:
    build: .
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ}
    working_dir: /slime
    shm_size: 1gb
    volumes:
      - type: bind
        source: .
        target: /slime
      - type: volume
        source: local
        target: /slime/local
      - type: bind
        source: ./local/docker/home
        target: /config
    ports:
      - 8000:8000
      - 3000:3000
      - 3001:3001
    depends_on:
      - chrome
      - firefox

  chrome:
    image: selenium/standalone-chromium:149.0-20260606
    ports:
      - 7900:7900

  firefox:
    image: selenium/standalone-firefox:152.0-20260606
    ports:
      - 7901:7900

volumes:
  local:
