#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

name: slime

services:
  # Produces a stateful, persistent SLIME container with a built-in Webtop desktop and the source directory mounted. Local changes
  # (to the local/ subdirectory, like installing JDKs, Rhino, Tomcat, and so forth) will persist between runs.
  #
  # Also used by the devcontainer implementation.
  #
  # The primary user interface for the container is Webtop (HTTP on 3000 and HTTPS on 3001 in-container).
  # Browser tests run from this service using local browser processes.
  local:
    build: .
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ}
    working_dir: /slime
    shm_size: 1gb
    volumes:
      - type: bind
        source: .
        target: /slime
      - type: volume
        source: local
        target: /slime/local
      - type: bind
        source: ./local/docker/home
        target: /config
      - type: bind
        source: ./local/agents
        target: /config/.agents
    ports:
      - 8000:8000
      - 3000:3000
      - 3001:3001

volumes:
  local:
