#!/bin/bash
#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

export PROJECT="$(dirname $0)"

SLIME="${PROJECT}"

if [ "$(uname)" == "Linux" ]; then
	#	We know (?) realpath is present because this is Linux
	if [ "$(realpath $0)" == "/mnt/hgfs/slime/wf" ]; then
		#	VMWare Linux guest with host source directory mounted
		if [ -z "${JSH_LOCAL_JDKS}" ]; then
			echo "source $(realpath ${SLIME}/contributor/macos/linuxvm/profile.bashrc)" >>"${HOME}/.bashrc"
			source ${SLIME}/contributor/macos/linuxvm/profile.bashrc
		fi
		if [ ! -h "${HOME}/src" ]; then
			ln -s /mnt/hgfs/slime ${HOME}/src
		fi
	fi
fi

#	For now, run all SLIME wf commands under JDK 8 with Rhino

if [ -z "${SLIME_WF_JDK_8}" ]; then
	SLIME_WF_JDK_8="${SLIME}/local/jdk/8"
fi

if [ ! -d "${SLIME_WF_JDK_8}" ]; then
	${SLIME}/jsh.bash --add-jdk-8
fi
LIB="${JSH_SHELL_LIB:-${SLIME}/local/jsh/lib}"
if [ ! -f "${LIB}/js.jar" ]; then
	${SLIME}/jsh.bash ${SLIME}/jsh/tools/install/rhino.jsh.js
fi
export JSH_LAUNCHER_JDK_HOME="${SLIME_WF_JDK_8}"

${PROJECT}/tools/wf.bash "$@"
