#!/bin/bash
#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

#	First argument is the JDK version to use
if [ -z "$1" ]; then
	>&2 echo "Required: JDK version to use."
	exit 1
fi

export JDK_VERSION="$1"
shift 1

$(dirname $0)/test-docker-clean-command $JDK_VERSION ./jsh "$@"
