#!/bin/bash
#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

#	Specify SLIME_WF_JDK_VERSION=n to run with different JDK; for example, SLIME_WF_JDK_VERSION=8

SLIME="$(dirname $0)/../.."

rm -Rf ${SLIME}/local/*

${SLIME}/jsh --add-jdk-8
${SLIME}/jsh --add-jdk-11
${SLIME}/jsh --add-jdk-17
${SLIME}/jsh --add-jdk-21

env JSH_LAUNCHER_BASH_DEBUG=1 SLIME_WF_BASH_DEBUG=1 ${SLIME}/wf check --docker >${SLIME}/local/devcontainer-check.txt 2>&1
