#!/bin/bash
#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

$(dirname $0)/simulate-new-container

SLIME="$(dirname $0)/../.."
/bin/bash ${SLIME}/jsh ${SLIME}/contributor/devcontainer/rhino-debugger.jsh.js
env JSH_DEBUG_SCRIPT=rhino /bin/bash ${SLIME}/jsh ${SLIME}/contributor/devcontainer/rhino-debugger.jsh.js
