name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker compose -f contributor/docker-compose.yaml build test
      - name: Run the linting and tests
        run: docker compose -f contributor/docker-compose.yaml run test
