#	LICENSE
#	This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
#	distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#	END LICENSE

name: test-jdk11
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Docker to create image, and then run the linting and tests
        env:
          SLIME_TEST_NO_WF_SUBMODULE_RESET: 1
          SLIME_TEST_JRUNSCRIPT_SHARD: ${{ matrix.shard }}
        run: contributor/suite-docker-jrunscript 11
